// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"github.com/quangdvn/go-ec/internal/controllers"
	"github.com/quangdvn/go-ec/internal/repositories"
	"github.com/quangdvn/go-ec/internal/services"
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controllers.UserController, error) {
	iUserRepository := repositories.NewUserRepository()
	iUserService := services.NewUserService(iUserRepository)
	userController := controllers.NewUserController(iUserService)
	return userController, nil
}
