server:
  port: 8082
  mode: "dev"
mysql:
  host: "localhost"
  port: 8811
  username: "admin"
  password: "mysql"
  dbname: "go-ec"
  charset: utf8mb4
  collation: utf8mb4_general_ci
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
  connMaxIdleTime: 3600
  # logMode: false
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 7
  compress: true
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  database: 0
  pool_size: 100
